services:
   name: yacma
    type: web
    env: docker
    repo: https://github.com/username/repo-name
    plan: free
    region: oregon
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
